development: &defaults
  app_id: X
  client_id: 368e1738eba0fe36b5b7e3449b3b3c87
  client_secret: X
  perms: manage_pages, offline_access
  page_id: detroitzoo


test:
  <<: *defaults

production:
  <<: *defaults
